apiVersion: v1
kind: Namespace
metadata:
  name: reloader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: reloader
    meta.helm.sh/release-namespace: reloader
  labels:
    app: reloader-reloader
    app.kubernetes.io/managed-by: Helm
    chart: reloader-v0.0.118
    heritage: Helm
    release: reloader
  name: reloader-reloader
  namespace: reloader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: reloader
    meta.helm.sh/release-namespace: reloader
  labels:
    app: reloader-reloader
    app.kubernetes.io/managed-by: Helm
    chart: reloader-v0.0.118
    heritage: Helm
    release: reloader
  name: reloader-reloader-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - list
  - get
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - deployments
  - daemonsets
  verbs:
  - list
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: reloader
    meta.helm.sh/release-namespace: reloader
  labels:
    app: reloader-reloader
    app.kubernetes.io/managed-by: Helm
    chart: reloader-v0.0.118
    heritage: Helm
    release: reloader
  name: reloader-reloader-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reloader-reloader-role
subjects:
- kind: ServiceAccount
  name: reloader-reloader
  namespace: reloader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: reloader
    meta.helm.sh/release-namespace: reloader
  labels:
    app: reloader-reloader
    app.kubernetes.io/managed-by: Helm
    chart: reloader-v0.0.118
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: reloader
    version: v0.0.118
  name: reloader-reloader
  namespace: reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader-reloader
      release: reloader
  template:
    metadata:
      labels:
        app: reloader-reloader
        app.kubernetes.io/managed-by: Helm
        chart: reloader-v0.0.118
        group: com.stakater.platform
        heritage: Helm
        provider: stakater
        release: reloader
        version: v0.0.118
    spec:
      containers:
      - image: stakater/reloader:v0.0.118
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: http
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: reloader-reloader
        ports:
        - containerPort: 9090
          name: http
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: http
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: reloader-reloader
